# Generated by scripts/bootstrap-state.sh — safe to commit
terraform {
  backend "s3" {
    bucket         = "checkpoint-demo-tfstate-796494636588"
    key            = "checkpoint-demo/terraform.tfstate"
    region         = "ap-southeast-2"
    dynamodb_table = "checkpoint-demo-tfstate-lock"
    encrypt        = true
  }
}
