- name: Test Check Point API Connection
  hosts: checkpoint
  connection: httpapi
  gather_facts: no
  tasks:
    - name: Show API versions
      check_point.mgmt.cp_mgmt_show_api_versions:
        auto_publish_session: true
      register: api_versions

    - name: Debug output
      debug:
        var: api_versions