- name: Test Check Point API Connection
  hosts: checkpoint
  tasks:
    - name: Retrieve API versions
      check_point.mgmt.cp_mgmt_show_api_versions:
        server: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: no