#!/usr/bin/env bash
# =============================================================================
# bootstrap-state.sh
#
# Creates the S3 bucket and DynamoDB table required for Terraform remote state.
# Run ONCE before the first terraform init. Safe to re-run — skips resources
# that already exist.
#
# Prerequisites:
#   - AWS CLI installed and configured (export AWS_PROFILE=checkpoint-demo)
#   - Sufficient IAM permissions (s3:CreateBucket, dynamodb:CreateTable)
#
# Usage:
#   bash scripts/bootstrap-state.sh
# =============================================================================

set -euo pipefail

# Disable AWS CLI pager so output never opens in less/vim
export AWS_PAGER=""

REGION="ap-southeast-2"
BACKEND_FILE="terraform/backend.tf"

echo ""
echo "================================================="
echo " Terraform State Bootstrap"
echo "================================================="

# Derive a unique bucket name from the AWS account ID
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
BUCKET_NAME="checkpoint-demo-tfstate-${ACCOUNT_ID}"
TABLE_NAME="checkpoint-demo-tfstate-lock"

echo " Account ID:     $ACCOUNT_ID"
echo " S3 bucket:      $BUCKET_NAME"
echo " DynamoDB table: $TABLE_NAME"
echo " Region:         $REGION"
echo ""

# ── S3 Bucket ─────────────────────────────────────────────────────────────────
if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
  echo "✓ S3 bucket already exists — skipping creation"
else
  echo "→ Creating S3 bucket..."
  aws s3api create-bucket \
    --bucket "$BUCKET_NAME" \
    --region "$REGION" \
    --create-bucket-configuration LocationConstraint="$REGION"

  echo "→ Enabling versioning..."
  aws s3api put-bucket-versioning \
    --bucket "$BUCKET_NAME" \
    --versioning-configuration Status=Enabled

  echo "→ Enabling server-side encryption..."
  aws s3api put-bucket-encryption \
    --bucket "$BUCKET_NAME" \
    --server-side-encryption-configuration '{
      "Rules": [{
        "ApplyServerSideEncryptionByDefault": {
          "SSEAlgorithm": "AES256"
        },
        "BucketKeyEnabled": true
      }]
    }'

  echo "→ Blocking all public access..."
  aws s3api put-public-access-block \
    --bucket "$BUCKET_NAME" \
    --public-access-block-configuration \
      BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

  echo "✓ S3 bucket created and secured"
fi

# ── DynamoDB Table ─────────────────────────────────────────────────────────────
if aws dynamodb describe-table --table-name "$TABLE_NAME" --region "$REGION" 2>/dev/null | grep -q ACTIVE; then
  echo "✓ DynamoDB table already exists — skipping creation"
else
  echo "→ Creating DynamoDB lock table..."
  aws dynamodb create-table \
    --table-name "$TABLE_NAME" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "$REGION"

  echo "→ Waiting for table to become active..."
  aws dynamodb wait table-exists --table-name "$TABLE_NAME" --region "$REGION"
  echo "✓ DynamoDB table created"
fi

# ── Write backend.tf ───────────────────────────────────────────────────────────
echo ""
echo "→ Writing $BACKEND_FILE..."
mkdir -p terraform

cat > "$BACKEND_FILE" <<EOF
# Generated by scripts/bootstrap-state.sh — safe to commit
terraform {
  backend "s3" {
    bucket         = "${BUCKET_NAME}"
    key            = "checkpoint-demo/terraform.tfstate"
    region         = "${REGION}"
    dynamodb_table = "${TABLE_NAME}"
    encrypt        = true
  }
}
EOF

echo "✓ $BACKEND_FILE written"

echo ""
echo "================================================="
echo " ✅  Bootstrap complete!"
echo ""
echo " Next steps:"
echo "   cd terraform"
echo "   terraform init"
echo "   git add ../terraform/backend.tf"
echo "   git commit -m 'Add generated Terraform backend config'"
echo "================================================="
echo ""
