apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkpoint-firewall-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Deim0s13/ansible-checkpoint-demo.git'
    targetRevision: main
    path: 'kubernetes/manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
