apiVersion: batch/v1
kind: Job
metadata:
  name: run-ansible-playbook
spec:
  template:
    spec:
      imagePullSecrets:
      - name: quay-regcred
      containers:
      - name: ansible-runner
        image: quay.io/rh-ee-pleathen/ansible-checkpoint:latest
        command: ["ansible-playbook", "-i", "/app/ansible/inventory/hosts.ini", "/app/ansible/playbooks/update_firewall.yml", "--vault-password-file", "/vault/.vault_pass"]
        volumeMounts:
          - name: vault-pass
            mountPath: /vault
      volumes:
      - name: vault-pass
        secret:
          secretName: ansible-vault-pass
      restartPolicy: Never