apiVersion: batch/v1
kind: Job
metadata:
  name: run-ansible-playbook
spec:
  template:
    spec:
      containers:
      - name: ansible
        image: williamyeh/ansible:alpine3
        command: ["/bin/sh", "-c"]
        args:
          - ansible-playbook /playbooks/update_firewall.yml --vault-password-file /vault/.vault_pass
        volumeMounts:
        - name: playbooks
          mountPath: /playbooks
        - name: vault-pass
          mountPath: /vault
      volumes:
      - name: playbooks
        configMap:
          name: ansible-playbooks
      - name: vault-pass
        secret:
          secretName: ansible-vault-pass
      restartPolicy: OnFailure
