apiVersion: batch/v1
kind: Job
metadata:
  name: run-ansible-playbook
spec:
  template:
    spec:
      containers:
      - name: ansible-runner
        image: quay.io/rh-ee-pleathen/ansible-checkpoint:latest
        command: ["ansible-playbook", "/app/ansible/playbooks/update_firewall.yml"]
        volumeMounts:
          - name: vault-pass
            mountPath: /vault
      volumes:
      - name: vault-pass
        secret:
          secretName: ansible-vault-pass
      restartPolicy: Never